import type { RotationRequirement } from "../types/rotation";

export const NIGHT_FLOAT_ROTATION_IDS = {
  pgy1TwoNorthCcu: "2n-ccu-pgy1-nf",
  pgy1FourNorthThreeWest: "4n-3w-pgy1-nf",
  pgy2TwoNorthCcu: "2n-ccu-pgy2-nf",
  pgy2FourNorthThreeWest: "4n-3w-pgy2-nf",
  pgy3: "pgy3-nf",
  pgy3NfAmb: "pgy3-nf-amb",
} as const;

export const OLD_GENERIC_NIGHT_FLOAT_ROTATION_ID = "night-float";
export const LEGACY_TWO_NORTH_CCU_BLOCK_ROTATION_ID = "2n-ccu";

export const DEFAULT_ROTATIONS: RotationRequirement[] = [
  {
    id: "vacation",
    name: "Vacation",
    category: "Vacation",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1", "PGY-2", "PGY-3"],
    capacityMode: "unlimited",
    aliases: ["vac", "pto", "maternity vacation", "maternity/vacation"],
    active: true,
    displayOrder: 1,
  },
  {
    id: "elective",
    name: "Elective",
    category: "Elective",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-2", "PGY-3"],
    capacityMode: "unlimited",
    aliases: ["electives"],
    active: true,
    displayOrder: 2,
  },
  {
    id: "er",
    name: "ER",
    category: "Emergency Medicine",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-3"],
    capacityMode: "unlimited",
    aliases: ["emergency", "emergency room", "ed"],
    active: true,
    displayOrder: 3,
  },
  {
    id: "2n",
    name: "2N",
    category: "Ward",
    requiredPGY1: 3,
    requiredPGY2: 2,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1", "PGY-2"],
    overrideAllowedPGY: ["PGY-3"],
    staffingSlots: [
      { id: "2na-pgy1", label: "2NA PGY1", required: 2, normalPGY: ["PGY-1"] },
      { id: "2na-pgy2", label: "2NA PGY2", required: 1, normalPGY: ["PGY-2"] },
      { id: "2nc-pgy1", label: "2NC PGY1", required: 1, normalPGY: ["PGY-1"] },
      {
        id: "2nc-senior",
        label: "2NC Senior",
        required: 1,
        normalPGY: ["PGY-2"],
        overridePGY: ["PGY-3"],
      },
    ],
    aliases: ["2 north", "2na", "2nc", "2n floor"],
    active: true,
    displayOrder: 4,
  },
  {
    id: "4n",
    name: "4N",
    category: "Ward",
    requiredPGY1: 4,
    requiredPGY2: 1,
    requiredPGY3: 1,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1", "PGY-2", "PGY-3"],
    staffingSlots: [
      { id: "4n-pgy1", label: "4N PGY1", required: 4, normalPGY: ["PGY-1"] },
      { id: "4n-pgy2", label: "4N PGY2 Senior", required: 1, normalPGY: ["PGY-2"] },
      { id: "4n-pgy3", label: "4N PGY3 Senior", required: 1, normalPGY: ["PGY-3"] },
    ],
    aliases: ["4 north"],
    active: true,
    displayOrder: 5,
  },
  {
    id: "tele",
    name: "Tele",
    category: "Ward",
    requiredPGY1: 3,
    requiredPGY2: 1,
    requiredPGY3: 1,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1", "PGY-2", "PGY-3"],
    staffingSlots: [
      { id: "tele-pgy1", label: "Tele PGY1", required: 3, normalPGY: ["PGY-1"] },
      { id: "tele-pgy2", label: "Tele PGY2 Senior", required: 1, normalPGY: ["PGY-2"] },
      { id: "tele-pgy3", label: "Tele PGY3 Senior", required: 1, normalPGY: ["PGY-3"] },
    ],
    aliases: ["telemetry"],
    active: true,
    displayOrder: 6,
  },
  {
    id: "3w",
    name: "3W",
    category: "Ward",
    requiredPGY1: 1,
    requiredPGY2: 1,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1", "PGY-2"],
    staffingSlots: [
      { id: "3w-pgy1", label: "3W PGY1", required: 1, normalPGY: ["PGY-1"] },
      { id: "3w-pgy2", label: "3W PGY2 Senior", required: 1, normalPGY: ["PGY-2"] },
    ],
    aliases: ["3 west"],
    active: true,
    displayOrder: 7,
  },
  {
    id: "micu",
    name: "MICU",
    category: "ICU",
    requiredPGY1: 4,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 2,
    normalAllowedPGY: ["PGY-1", "PGY-2", "PGY-3"],
    staffingSlots: [
      { id: "micu-pgy1", label: "MICU PGY1", required: 4, normalPGY: ["PGY-1"] },
      {
        id: "micu-senior",
        label: "MICU Senior",
        required: 2,
        normalPGY: ["PGY-2", "PGY-3"],
      },
    ],
    aliases: ["medical icu", "icu"],
    active: true,
    displayOrder: 8,
  },
  {
    id: "pulm",
    name: "Pulm",
    category: "Consult",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 2,
    normalAllowedPGY: ["PGY-2", "PGY-3"],
    staffingSlots: [
      {
        id: "pulm-senior",
        label: "Pulmonary Senior",
        required: 2,
        normalPGY: ["PGY-2", "PGY-3"],
      },
    ],
    aliases: ["pulmonary", "pulmonology", "pulm as pgy2", "pulm as pgy3"],
    active: true,
    displayOrder: 9,
  },
  {
    id: "ccu-cardio",
    name: "CCU/Cardio",
    category: "Consult",
    requiredPGY1: 0,
    requiredPGY2: 1,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-2"],
    overrideAllowedPGY: ["PGY-3"],
    staffingSlots: [
      {
        id: "ccu-cardio-senior",
        label: "CCU/Cardio Senior",
        required: 1,
        normalPGY: ["PGY-2"],
        overridePGY: ["PGY-3"],
      },
    ],
    aliases: ["cardio", "cardiology", "ccu", "cardio/ccu", "cardiology/ccu"],
    active: true,
    displayOrder: 10,
  },
  {
    id: "ambulatory",
    name: "Ambulatory",
    category: "Ambulatory",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1", "PGY-2", "PGY-3"],
    capacityMode: "unlimited",
    aliases: ["amb", "clinic"],
    active: true,
    displayOrder: 11,
  },
  {
    id: "neuro",
    name: "Neuro",
    category: "Consult",
    requiredPGY1: 0,
    requiredPGY2: 1,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-2"],
    staffingSlots: [
      { id: "neuro-pgy2", label: "Neuro PGY2", required: 1, normalPGY: ["PGY-2"] },
    ],
    aliases: ["neurology"],
    active: true,
    displayOrder: 12,
  },
  {
    id: "id",
    name: "ID",
    category: "Consult",
    requiredPGY1: 1,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 1,
    normalAllowedPGY: ["PGY-1", "PGY-2", "PGY-3"],
    staffingSlots: [
      { id: "id-pgy1", label: "ID PGY1", required: 1, normalPGY: ["PGY-1"] },
      {
        id: "id-senior",
        label: "ID Senior",
        required: 1,
        normalPGY: ["PGY-2", "PGY-3"],
      },
    ],
    aliases: ["infectious disease", "infectious diseases", "id consult"],
    active: true,
    displayOrder: 13,
  },
  {
    id: NIGHT_FLOAT_ROTATION_IDS.pgy1TwoNorthCcu,
    name: "2N-CCU PGY1 NF",
    category: "Night Float",
    requiredPGY1: 1,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1"],
    staffingSlots: [
      { id: "2n-ccu-pgy1-nf", label: "2N-CCU PGY1 NF", required: 1, normalPGY: ["PGY-1"] },
    ],
    aliases: ["2n ccu pgy1 nf", "2n-ccu intern nf"],
    active: true,
    displayOrder: 14,
  },
  {
    id: NIGHT_FLOAT_ROTATION_IDS.pgy1FourNorthThreeWest,
    name: "4N-3W PGY1 NF",
    category: "Night Float",
    requiredPGY1: 1,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1"],
    staffingSlots: [
      { id: "4n-3w-pgy1-nf", label: "4N-3W PGY1 NF", required: 1, normalPGY: ["PGY-1"] },
    ],
    aliases: ["4n 3w pgy1 nf", "4n-3w intern nf"],
    active: true,
    displayOrder: 15,
  },
  {
    id: NIGHT_FLOAT_ROTATION_IDS.pgy2TwoNorthCcu,
    name: "2N-CCU PGY2 NF",
    category: "Night Float",
    requiredPGY1: 0,
    requiredPGY2: 1,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-2"],
    staffingSlots: [
      { id: "2n-ccu-pgy2-nf", label: "2N-CCU PGY2 NF", required: 1, normalPGY: ["PGY-2"] },
    ],
    aliases: ["2n ccu pgy2 nf", "2n-ccu senior nf"],
    active: true,
    displayOrder: 16,
  },
  {
    id: NIGHT_FLOAT_ROTATION_IDS.pgy2FourNorthThreeWest,
    name: "4N-3W PGY2 NF",
    category: "Night Float",
    requiredPGY1: 0,
    requiredPGY2: 1,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-2"],
    staffingSlots: [
      { id: "4n-3w-pgy2-nf", label: "4N-3W PGY2 NF", required: 1, normalPGY: ["PGY-2"] },
    ],
    aliases: ["4n 3w pgy2 nf", "4n-3w senior nf"],
    active: true,
    displayOrder: 17,
  },
  {
    id: NIGHT_FLOAT_ROTATION_IDS.pgy3,
    name: "PGY3 NF",
    category: "Night Float",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 1,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-3"],
    staffingSlots: [
      { id: "pgy3-nf", label: "PGY3 NF", required: 1, normalPGY: ["PGY-3"] },
    ],
    aliases: ["nf", "night float", "pgy3 night float"],
    active: true,
    displayOrder: 18,
  },
  {
    id: NIGHT_FLOAT_ROTATION_IDS.pgy3NfAmb,
    name: "PGY3 NF/Amb",
    category: "Night Float",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-3"],
    capacityMode: "unlimited",
    aliases: ["nf amb", "nf-amb", "amb nf", "amb-nf", "pgy3 nf amb"],
    active: true,
    displayOrder: 19,
  },
  {
    id: "gi",
    name: "GI",
    category: "Consult",
    requiredPGY1: 0,
    requiredPGY2: 1,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-2"],
    staffingSlots: [
      { id: "gi-pgy2", label: "GI PGY2", required: 1, normalPGY: ["PGY-2"] },
    ],
    aliases: ["gastro", "gastroenterology"],
    active: true,
    displayOrder: 20,
  },
  {
    id: "heme-onc",
    name: "Heme-Onc",
    category: "Consult",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 1,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-3"],
    staffingSlots: [
      { id: "heme-onc-pgy3", label: "Heme-Onc PGY3", required: 1, normalPGY: ["PGY-3"] },
    ],
    aliases: ["heme onc", "hem onc", "heme/onc", "hematology oncology"],
    active: true,
    displayOrder: 21,
  },
  {
    id: "nephro-rheum-endo",
    name: "Nephro-Rheum-Endo",
    category: "Consult",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 1,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-3"],
    staffingSlots: [
      {
        id: "nephro-rheum-endo-pgy3",
        label: "Nephro-Rheum-Endo PGY3",
        required: 1,
        normalPGY: ["PGY-3"],
      },
    ],
    aliases: [
      "nephro endo rheum",
      "nephro/endo/rheum",
      "nephro rheum endo",
      "endo rheum nephro",
      "nre",
    ],
    active: true,
    displayOrder: 22,
  },
  {
    id: "admission",
    name: "Admission",
    category: "Admission",
    requiredPGY1: 1,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 1,
    normalAllowedPGY: ["PGY-1", "PGY-2", "PGY-3"],
    staffingSlots: [
      { id: "admission-pgy1", label: "Admission PGY1", required: 1, normalPGY: ["PGY-1"] },
      {
        id: "admission-senior",
        label: "Admission Senior",
        required: 1,
        normalPGY: ["PGY-2", "PGY-3"],
      },
    ],
    aliases: ["admit", "admitting"],
    active: true,
    displayOrder: 23,
  },
  {
    id: "jeopardy",
    name: "Jeopardy",
    category: "Jeopardy",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: ["PGY-1", "PGY-2", "PGY-3"],
    capacityMode: "unlimited",
    aliases: ["backup", "jeop"],
    active: true,
    displayOrder: 24,
  },
  {
    id: LEGACY_TWO_NORTH_CCU_BLOCK_ROTATION_ID,
    name: "2N-CCU (Legacy Block)",
    category: "Ward",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: [],
    capacityMode: "unlimited",
    aliases: [],
    active: false,
    displayOrder: 998,
  },
  {
    id: OLD_GENERIC_NIGHT_FLOAT_ROTATION_ID,
    name: "Night Float",
    category: "Night Float",
    requiredPGY1: 0,
    requiredPGY2: 0,
    requiredPGY3: 0,
    requiredSenior: 0,
    normalAllowedPGY: [],
    capacityMode: "unlimited",
    aliases: [],
    active: false,
    displayOrder: 999,
  },
];
