import {
  collection,
  doc,
  getDocs,
  orderBy,
  query,
  setDoc,
} from "firebase/firestore";

import { db } from "../config/firebase";
import type { RotationRequirement } from "../types/rotation";

const rotationsCollection = collection(db, "rotations");

export const NIGHT_FLOAT_ROTATION_IDS = {
  pgy1TwoNorthCcu: "2n-ccu-pgy1-nf",
  pgy1FourNorthThreeWest: "4n-3w-pgy1-nf",
  pgy2TwoNorthCcu: "2n-ccu-pgy2-nf",
  pgy2FourNorthThreeWest: "4n-3w-pgy2-nf",
  pgy3: "pgy3-nf",
  pgy3NfAmb: "pgy3-nf-amb",
} as const;

export const OLD_GENERIC_NIGHT_FLOAT_ROTATION_ID = "night-float";

export async function getRotations(): Promise<RotationRequirement[]> {
  const q = query(rotationsCollection, orderBy("displayOrder", "asc"));
  const snapshot = await getDocs(q);

  return snapshot.docs.map((docSnap) => ({
    id: docSnap.id,
    ...(docSnap.data() as Omit<RotationRequirement, "id">),
  }));
}

export async function seedDefaultRotations() {
  const rotations: RotationRequirement[] = [
    {
      id: "vacation",
      name: "Vacation",
      category: "Vacation",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 0,
      active: true,
      displayOrder: 1,
    },
    {
      id: "elective",
      name: "Elective",
      category: "Elective",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 0,
      active: true,
      displayOrder: 2,
    },

    {
      id: "2n",
      name: "2N",
      category: "Ward",
      requiredPGY1: 3,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 3,
    },
    {
      id: "2n-ccu",
      name: "2N-CCU",
      category: "Ward",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 4,
    },
    {
      id: "4n",
      name: "4N",
      category: "Ward",
      requiredPGY1: 4,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 2,
      active: true,
      displayOrder: 5,
    },
    {
      id: "tele",
      name: "Tele",
      category: "Ward",
      requiredPGY1: 3,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 2,
      active: true,
      displayOrder: 6,
    },

    {
      id: "pulm",
      name: "Pulm",
      category: "Consult",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 2,
      active: true,
      displayOrder: 7,
    },
    {
      id: "ccu-cardio",
      name: "CCU/Cardio",
      category: "Consult",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 8,
    },
    {
      id: "ambulatory",
      name: "Ambulatory",
      category: "Ambulatory",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 0,
      active: true,
      displayOrder: 9,
    },
    {
      id: "neuro",
      name: "Neuro",
      category: "Consult",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 10,
    },
    {
      id: "id",
      name: "ID",
      category: "Consult",
      requiredPGY1: 1,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 11,
    },

    {
      id: NIGHT_FLOAT_ROTATION_IDS.pgy1TwoNorthCcu,
      name: "2N-CCU PGY1 NF",
      category: "Night Float",
      requiredPGY1: 1,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 0,
      active: true,
      displayOrder: 12,
    },
    {
      id: NIGHT_FLOAT_ROTATION_IDS.pgy1FourNorthThreeWest,
      name: "4N-3W PGY1 NF",
      category: "Night Float",
      requiredPGY1: 1,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 0,
      active: true,
      displayOrder: 13,
    },
    {
      id: NIGHT_FLOAT_ROTATION_IDS.pgy2TwoNorthCcu,
      name: "2N-CCU PGY2 NF",
      category: "Night Float",
      requiredPGY1: 0,
      requiredPGY2: 1,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 14,
    },
    {
      id: NIGHT_FLOAT_ROTATION_IDS.pgy2FourNorthThreeWest,
      name: "4N-3W PGY2 NF",
      category: "Night Float",
      requiredPGY1: 0,
      requiredPGY2: 1,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 15,
    },
    {
      id: NIGHT_FLOAT_ROTATION_IDS.pgy3,
      name: "PGY3 NF",
      category: "Night Float",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 1,
      requiredSenior: 1,
      active: true,
      displayOrder: 16,
    },
    {
      id: NIGHT_FLOAT_ROTATION_IDS.pgy3NfAmb,
      name: "PGY3 NF/Amb",
      category: "Night Float",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 0,
      active: true,
      displayOrder: 17,
    },

    {
      id: "3w",
      name: "3W",
      category: "Ward",
      requiredPGY1: 2,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 18,
    },
    {
      id: "micu",
      name: "MICU",
      category: "ICU",
      requiredPGY1: 4,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 2,
      active: true,
      displayOrder: 19,
    },
    {
      id: "gi",
      name: "GI",
      category: "Consult",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 20,
    },
    {
      id: "heme-onc",
      name: "Heme-Onc",
      category: "Consult",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 21,
    },
    {
      id: "nephro-rheum-endo",
      name: "Nephro-Rheum-Endo",
      category: "Consult",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 22,
    },
    {
      id: "admission",
      name: "Admission",
      category: "Admission",
      requiredPGY1: 1,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 1,
      active: true,
      displayOrder: 23,
    },
    {
      id: "jeopardy",
      name: "Jeopardy",
      category: "Jeopardy",
      requiredPGY1: 1,
      requiredPGY2: 1,
      requiredPGY3: 1,
      requiredSenior: 0,
      active: true,
      displayOrder: 24,
    },

    {
      id: OLD_GENERIC_NIGHT_FLOAT_ROTATION_ID,
      name: "Night Float",
      category: "Night Float",
      requiredPGY1: 0,
      requiredPGY2: 0,
      requiredPGY3: 0,
      requiredSenior: 0,
      active: false,
      displayOrder: 999,
    },
  ];

  for (const rotation of rotations) {
    const { id, ...data } = rotation;
    await setDoc(doc(db, "rotations", id), data, { merge: true });
  }
}