export type AppPage =
  | "whos-on"
  | "directory"
  | "residents"
  | "attendings"
  | "attending-call-schedule"
  | "schedule"
  | "block-schedule"
  | "lectures"
  | "coverage-rules"
  | "integrity"
  | "calendar-subscription"
  | "backup-restore"
  | "invites"
  | "call-swaps"
  | "vacation"
  | "external-sync"
  | "settings";
