import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Card, CardContent, CircularProgress, IconButton, Stack, Typography } from "@mui/material";
import ChevronLeftIcon from "@mui/icons-material/ChevronLeft";
import ChevronRightIcon from "@mui/icons-material/ChevronRight";
import SourceSyncBanner from "../components/SourceSyncBanner";
import { getSourceLectures, type SourceRecord } from "../services/sourceSchedulerService";
const monthValue=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;
const bounds=(month:string)=>{const [y,m]=month.split("-").map(Number);return{start:`${month}-01`,end:`${month}-${String(new Date(y,m,0).getDate()).padStart(2,"0")}`}};
const shift=(month:string,amount:number)=>{const[y,m]=month.split("-").map(Number);return monthValue(new Date(y,m-1+amount,1))};
const slotTimes:Record<string,string>={am_8:"8:00 AM–9:00 AM",pm_12:"12:00 PM–1:00 PM"};
export default function SourceLectureSchedulePage(){const[month,setMonth]=useState(monthValue(new Date())),[items,setItems]=useState<SourceRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const range=useMemo(()=>bounds(month),[month]);useEffect(()=>{setLoading(true);void getSourceLectures(range.start,range.end).then(setItems).catch(()=>setError("Unable to load the lecture schedule.")).finally(()=>setLoading(false));},[range.start,range.end]);const grouped=useMemo(()=>{const map=new Map<string,SourceRecord[]>();for(const item of items){const date=String(item.date);map.set(date,[...(map.get(date)||[]),item]);}return[...map.entries()].sort(([a],[b])=>a.localeCompare(b));},[items]);return <Box><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h4" fontWeight={900}>Lecture Schedule</Typography><Typography color="text.secondary">Read-only conferences supplied by the Source Scheduler.</Typography></Box><Stack direction="row" alignItems="center"><IconButton onClick={()=>setMonth(shift(month,-1))}><ChevronLeftIcon/></IconButton><Typography fontWeight={900}>{new Date(`${month}-01T12:00:00`).toLocaleDateString("en-US",{month:"long",year:"numeric"})}</Typography><IconButton onClick={()=>setMonth(shift(month,1))}><ChevronRightIcon/></IconButton></Stack></Stack><SourceSyncBanner />{error&&<Alert severity="error">{error}</Alert>}{loading?<Stack alignItems="center" sx={{py:8}}><CircularProgress/></Stack>:grouped.length===0?<Alert severity="info">No lectures are scheduled this month.</Alert>:<Stack spacing={1}>{grouped.map(([date,lectures])=><Card key={date}><CardContent><Typography fontWeight={900} sx={{mb:.8}}>{new Date(`${date}T12:00:00`).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})}</Typography>{lectures.map(item=><Box key={String(item.id)} sx={{border:"1px solid",borderColor:"divider",borderRadius:1.5,p:1,mb:.7}}><Typography fontWeight={900}>{String(item.title)}</Typography><Typography fontSize={13} color="text.secondary">{slotTimes[String(item.slot)]||String(item.slot)}{item.presenter?` · ${item.presenter}`:""}{item.location?` · ${item.location}`:""}</Typography></Box>)}</CardContent></Card>)}</Stack>}</Box>}
