import { useEffect, useState } from "react";
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from "@mui/material";
import { createResident } from "../services/residentService";
import { createAttending } from "../services/attendingService";
import { saveSourceProfileLink, type SourcePersonType } from "../services/sourceProfileLinkService";
import type { Resident, PGY } from "../types/resident";
import type { Attending } from "../types/attending";

type Profile = Resident | Attending;
export default function SourceProfileLinkDialog({open,sourceName,personType,profiles,onClose,onSaved}:{open:boolean;sourceName:string;personType:SourcePersonType;profiles:Profile[];onClose:()=>void;onSaved:()=>void}){
  const[profileId,setProfileId]=useState("");const[mode,setMode]=useState<"existing"|"new">("existing");const[fullName,setFullName]=useState(sourceName);const[pgy,setPgy]=useState<PGY>("PGY-1");const[specialty,setSpecialty]=useState("");const[phone,setPhone]=useState("");const[error,setError]=useState("");const[saving,setSaving]=useState(false);
  useEffect(()=>{setFullName(sourceName);setProfileId("");setMode("existing");setError("")},[sourceName,open]);
  async function save(){try{setSaving(true);setError("");let id=profileId;if(mode==="new"){const clean=fullName.replace(/^dr\.?\s*/i,"").trim();const parts=clean.includes(",")?clean.split(",").reverse().map(x=>x.trim()):clean.split(/\s+/);const firstName=parts[0]||"Unknown";const lastName=parts.slice(1).join(" ")||"Unknown";if(personType==="resident")id=await createResident({firstName,lastName,displayName:lastName,email:"",pager:"",phone,pgy,role:"Resident",active:true});else id=await createAttending({firstName,lastName,displayName:`Dr. ${lastName}`,specialty,email:"",pager:"",phone,active:true,availableForScheduling:false,notes:"Created while linking Source Scheduler profile"});}if(!id)throw new Error("Select a profile or create a new one.");await saveSourceProfileLink(sourceName,personType,id);onSaved();onClose();}catch(err){setError(err instanceof Error?err.message:"Unable to save this profile link.")}finally{setSaving(false)}}
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Link Source Scheduler name</DialogTitle><DialogContent><Typography fontWeight={900} sx={{mb:1}}>{sourceName}</Typography>{error&&<Alert severity="error" sx={{mb:1}}>{error}</Alert>}<Stack direction="row" spacing={1} sx={{mb:1}}><Button variant={mode==="existing"?"contained":"outlined"} onClick={()=>setMode("existing")}>Existing profile</Button><Button variant={mode==="new"?"contained":"outlined"} onClick={()=>setMode("new")}>Create profile</Button></Stack>{mode==="existing"?<TextField select fullWidth label={`Select ${personType}`} value={profileId} onChange={e=>setProfileId(e.target.value)}>{profiles.filter(item=>item.active).map(item=><MenuItem key={item.id} value={item.id}>{item.displayName}</MenuItem>)}</TextField>:<Stack spacing={1}><TextField label="Full name" value={fullName} onChange={e=>setFullName(e.target.value)} helperText="Replace an initial with the complete first name before creating."/>{personType==="resident"?<TextField select label="PGY" value={pgy} onChange={e=>setPgy(e.target.value as PGY)}>{["PGY-1","PGY-2","PGY-3"].map(item=><MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField>:<TextField label="Specialty" value={specialty} onChange={e=>setSpecialty(e.target.value)}/>}<TextField label="Phone" value={phone} onChange={e=>setPhone(e.target.value)} /></Stack>}</DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>{saving?"Saving…":"Save link"}</Button></DialogActions></Dialog>
}
